version: '3.1'

services:
  postgres:
    image: postgres:13.10
    container_name: postgres-mine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty007
      POSTGRES_DB: postgres
    ports:
      - "5436:5432"
    networks:
      - my-network
  user-service:
    build:
      context: ./carbon-footprints
      dockerfile: Dockerfile
    container_name: my-app
    restart: always
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: qwerty007
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
    ports:
      - "8085:8085"
    networks:
      - my-network

volumes:
  postgres-data:

networks:
  my-network:

